name: Allphins Frontend STAGING Unit Testing
on:
  push:
    branches:
      - main

env:
  NODE_ENV: developement

  jobs:
  # create readme and store it as artifact
  create-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create README.md
        run: echo "Hello, World!" > README.md
      - name: Archive README.md
        uses: actions/upload-artifact@v2
        with:
          name: README
          path: README.md
